; Tile Pattern file for use with SMS Z80 Assembly programs
; By Steelfinger Studios
; Tile Pattern #0
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00  
; Tile Pattern #1
.DB $00 $FF $00 $00 
.DB $3F $C0 $00 $00 
.DB $40 $80 $00 $00 
.DB $9F $1F $00 $00 
.DB $BF $37 $00 $00 
.DB $BF $2F $00 $00 
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00  
; Tile Pattern #2
.DB $00 $FF $00 $00 
.DB $FF $00 $00 $00 
.DB $00 $00 $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #3
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00 
.DB $BF $3F $00 $00  
; Tile Pattern #4
.DB $FF $FF $00 $00 
.DB $F0 $F0 $00 $00 
.DB $E1 $E0 $00 $00 
.DB $C3 $C1 $00 $00 
.DB $C7 $C3 $00 $00 
.DB $CF $C7 $00 $00 
.DB $D8 $C8 $00 $00 
.DB $F0 $D0 $00 $00  
; Tile Pattern #5
.DB $FF $FF $00 $00 
.DB $C1 $C1 $00 $00 
.DB $83 $81 $00 $00 
.DB $07 $03 $00 $00 
.DB $CF $07 $00 $00 
.DB $FF $CF $00 $00 
.DB $07 $07 $00 $00 
.DB $03 $03 $00 $00  
; Tile Pattern #6
.DB $FF $FF $00 $00 
.DB $C0 $C0 $00 $00 
.DB $C1 $C0 $00 $00 
.DB $C3 $C1 $00 $00 
.DB $E7 $C3 $00 $00 
.DB $EF $E7 $00 $00 
.DB $F8 $E8 $00 $00 
.DB $F0 $F0 $00 $00  
; Tile Pattern #7
.DB $FF $FF $00 $00 
.DB $C1 $C1 $00 $00 
.DB $83 $81 $00 $00 
.DB $07 $03 $00 $00 
.DB $CF $07 $00 $00 
.DB $FF $CF $00 $00 
.DB $1F $1F $00 $00 
.DB $1F $1F $00 $00  
; Tile Pattern #8
.DB $E0 $E0 $00 $00 
.DB $FF $E0 $00 $00 
.DB $F3 $F3 $00 $00 
.DB $E0 $E0 $00 $00 
.DB $C0 $C0 $00 $00 
.DB $80 $80 $00 $00 
.DB $FF $80 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #9
.DB $03 $03 $00 $00 
.DB $E3 $03 $00 $00 
.DB $E3 $E3 $00 $00 
.DB $03 $03 $00 $00 
.DB $07 $03 $00 $00 
.DB $0F $07 $00 $00 
.DB $FF $0F $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #10
.DB $E0 $E0 $00 $00 
.DB $E3 $E0 $00 $00 
.DB $E3 $E3 $00 $00 
.DB $C1 $C1 $00 $00 
.DB $C1 $C1 $00 $00 
.DB $C1 $C1 $00 $00 
.DB $FF $C1 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #11
.DB $1F $1F $00 $00 
.DB $FF $1F $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #12
.DB $BF $3F $00 $00 
.DB $BF $2F $00 $00 
.DB $BF $37 $00 $00 
.DB $DF $5F $00 $00 
.DB $E0 $60 $00 $00 
.DB $E0 $7F $00 $00 
.DB $60 $BF $00 $00 
.DB $3F $C0 $00 $00  
; Tile Pattern #13
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $FF $FF $00 $00 
.DB $00 $00 $00 $00 
.DB $00 $FF $00 $00 
.DB $00 $FF $00 $00 
.DB $FF $00 $00 $00  
; Tile Pattern #14
.DB $03 $FF $00 $00 
.DB $07 $FF $00 $00 
.DB $0E $FE $00 $00 
.DB $0F $FE $00 $00 
.DB $0F $FF $00 $00 
.DB $0E $FE $00 $00 
.DB $07 $FE $00 $00 
.DB $03 $FF $00 $00  
; Tile Pattern #15
.DB $FF $FF $00 $00 
.DB $08 $08 $00 $00 
.DB $7A $08 $00 $00 
.DB $1E $1A $00 $00 
.DB $CE $0E $00 $00 
.DB $1C $0C $00 $00 
.DB $FF $1C $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #16
.DB $FF $FF $00 $00 
.DB $20 $20 $00 $00 
.DB $B6 $20 $00 $00 
.DB $F3 $B2 $00 $00 
.DB $F6 $F2 $00 $00 
.DB $60 $60 $00 $00 
.DB $FF $60 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #17
.DB $FF $FF $00 $00 
.DB $82 $82 $00 $00 
.DB $DB $82 $00 $00 
.DB $CF $CB $00 $00 
.DB $DB $CB $00 $00 
.DB $82 $82 $00 $00 
.DB $FF $82 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #18
.DB $FF $FF $00 $00 
.DB $38 $38 $00 $00 
.DB $7D $38 $00 $00 
.DB $7C $7C $00 $00 
.DB $6D $6C $00 $00 
.DB $08 $08 $00 $00 
.DB $FF $08 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #19
.DB $FF $FF $00 $00 
.DB $20 $20 $00 $00 
.DB $AA $20 $00 $00 
.DB $FB $AA $00 $00 
.DB $EA $EA $00 $00 
.DB $E0 $E0 $00 $00 
.DB $FF $E0 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #20
.DB $FF $FF $00 $00 
.DB $99 $99 $00 $00 
.DB $CB $89 $00 $00 
.DB $C3 $C3 $00 $00 
.DB $D3 $C3 $00 $00 
.DB $99 $91 $00 $00 
.DB $FF $99 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #21
.DB $FF $FF $00 $00 
.DB $8C $8C $00 $00 
.DB $7E $0C $00 $00 
.DB $66 $66 $00 $00 
.DB $76 $66 $00 $00 
.DB $8C $04 $00 $00 
.DB $FF $8C $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #22
.DB $FF $FF $00 $00 
.DB $10 $10 $00 $00 
.DB $DB $10 $00 $00 
.DB $78 $58 $00 $00 
.DB $DA $58 $00 $00 
.DB $12 $12 $00 $00 
.DB $FF $12 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #23
.DB $3F $FF $00 $00 
.DB $70 $F0 $00 $00 
.DB $E7 $E0 $00 $00 
.DB $F1 $E1 $00 $00 
.DB $FC $F0 $00 $00 
.DB $E1 $E0 $00 $00 
.DB $7F $E1 $00 $00 
.DB $3F $FF $00 $00  
; Tile Pattern #24
.DB $FF $FF $00 $00 
.DB $82 $82 $00 $00 
.DB $AB $82 $00 $00 
.DB $EF $AB $00 $00 
.DB $EF $EF $00 $00 
.DB $C7 $C7 $00 $00 
.DB $FF $C7 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #25
.DB $FF $FF $00 $00 
.DB $48 $48 $00 $00 
.DB $6D $48 $00 $00 
.DB $6D $6D $00 $00 
.DB $6D $6D $00 $00 
.DB $98 $08 $00 $00 
.DB $FF $98 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #26
.DB $FF $FF $00 $00 
.DB $60 $60 $00 $00 
.DB $AA $20 $00 $00 
.DB $BB $AA $00 $00 
.DB $AA $AA $00 $00 
.DB $60 $20 $00 $00 
.DB $FF $60 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #27
.DB $FF $FF $00 $00 
.DB $C7 $C7 $00 $00 
.DB $B2 $82 $00 $00 
.DB $BB $B2 $00 $00 
.DB $9B $9B $00 $00 
.DB $C6 $82 $00 $00 
.DB $FF $C6 $00 $00 
.DB $FF $FF $00 $00  
; Tile Pattern #28
.DB $FC $FF $00 $00 
.DB $0E $0F $00 $00 
.DB $7F $0F $00 $00 
.DB $1F $1F $00 $00 
.DB $CF $0F $00 $00 
.DB $1F $0F $00 $00 
.DB $FE $1F $00 $00 
.DB $FC $FF $00 $00  
; End of file
