#Emulicious settings file
#Sun Jun 14 13:39:52 JST 2026
AudioSync=false
CodeFontSize=13
FontSize=13
Recent0=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent1=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent2=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent3=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent4=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent5=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent6=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent7=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent8=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Recent9=/home/cameron/Z80-Dev/smsProjects/SMS-BG-Template/output.sms
Scale=2.5
Update=2
WindowEmuliciousHeight=533
WindowEmuliciousWidth=640
WindowEmuliciousX=616
WindowEmuliciousY=199
